// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class Activity
    {
        public string ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityImagePaht { get; set; }
        public string ActivityVideoPaht { get; set; }
        public string ActivityDetails { get; set; }
        public string ActivityBusinessId { get; set; }

        public virtual Business ActivityBusiness { get; set; }
    }
}