// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class Business
    {
        public Business()
        {
            Activity = new HashSet<Activity>();
            Map = new HashSet<Map>();
            Promotion = new HashSet<Promotion>();
            Raft = new HashSet<Raft>();
            Services = new HashSet<Services>();
        }

        public string BusinessId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessPassword { get; set; }
        public int? BusinessStatusId { get; set; }
        public string BusinessRegister { get; set; }
        public string BusinessTel { get; set; }
        public string BusinessIdline { get; set; }
        public string BusinessEmail { get; set; }
        public string BusinessBank { get; set; }
        public string BusinessAccountnumber { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessSubdistrict { get; set; }
        public string BusinessDistrict { get; set; }
        public string BusinessProvince { get; set; }
        public string BusinessZipcode { get; set; }

        public virtual StatusBusiness BusinessStatus { get; set; }
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<Map> Map { get; set; }
        public virtual ICollection<Promotion> Promotion { get; set; }
        public virtual ICollection<Raft> Raft { get; set; }
        public virtual ICollection<Services> Services { get; set; }
    }
}