// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class DetailServices
    {
        public string DetailservicesId { get; set; }
        public string DetailservicesServicesId { get; set; }
        public string DetailservicesRaftId { get; set; }

        public virtual Raft DetailservicesRaft { get; set; }
        public virtual Services DetailservicesServices { get; set; }
    }
}