// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class Map
    {
        public string MapId { get; set; }
        public string MapLatitude { get; set; }
        public string MapLongitude { get; set; }
        public string MapBusinessId { get; set; }

        public virtual Business MapBusiness { get; set; }
    }
}