// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class OrderServices
    {
        public string OsId { get; set; }
        public string OsServiceId { get; set; }
        public string OsOrderId { get; set; }

        public virtual Order OsOrder { get; set; }
        public virtual Services OsService { get; set; }
    }
}