// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class OrderDetails
    {
        public string OrderDetailsId { get; set; }
        public int? OrderDetailsPrice { get; set; }
        public string OrderDetailsOrderId { get; set; }
        public string OrderDetailsRaftId { get; set; }

        public virtual Order OrderDetailsOrder { get; set; }
        public virtual Raft OrderDetailsRaft { get; set; }
    }
}