// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class Raft
    {
        public Raft()
        {
            DetailServices = new HashSet<DetailServices>();
            OrderDetails = new HashSet<OrderDetails>();
        }

        public string RaftId { get; set; }
        public string RaftName { get; set; }
        public string RaftDetails { get; set; }
        public int? RaftPrice { get; set; }
        public string RaftImage { get; set; }
        public string RaftBusinessId { get; set; }

        public virtual Business RaftBusiness { get; set; }
        public virtual ICollection<DetailServices> DetailServices { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}