// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class Services
    {
        public Services()
        {
            DetailServices = new HashSet<DetailServices>();
            OrderServices = new HashSet<OrderServices>();
        }

        public string ServicesId { get; set; }
        public string ServicesName { get; set; }
        public string ServicesDetails { get; set; }
        public string ServicesImagePaht { get; set; }
        public string ServicesVedioPaht { get; set; }
        public int? ServicesPrice { get; set; }
        public string SerBusinessId { get; set; }

        public virtual Business SerBusiness { get; set; }
        public virtual ICollection<DetailServices> DetailServices { get; set; }
        public virtual ICollection<OrderServices> OrderServices { get; set; }
    }
}