// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class StatusOrder
    {
        public StatusOrder()
        {
            Order = new HashSet<Order>();
        }

        public int SorderId { get; set; }
        public string SorderName { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}