// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class User
    {
        public User()
        {
            Order = new HashSet<Order>();
        }

        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserTel { get; set; }
        public string UserEmail { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}