// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace APIRaft.Data
{
    public partial class ViewRafts
    {
        public string ServicesName { get; set; }
        public string ServicesId { get; set; }
        public int? ServicesPrice { get; set; }
        public string DetailservicesId { get; set; }
        public string ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityDetails { get; set; }
        public string BusinessId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessPassword { get; set; }
        public int? BusinessStatusId { get; set; }
        public string BusinessRegister { get; set; }
        public string BusinessTel { get; set; }
        public string BusinessIdline { get; set; }
        public string BusinessEmail { get; set; }
        public string BusinessBank { get; set; }
        public string BusinessAccountnumber { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessSubdistrict { get; set; }
        public string BusinessDistrict { get; set; }
        public string BusinessProvince { get; set; }
        public string BusinessZipcode { get; set; }
        public string PromotionId { get; set; }
        public string PromotionName { get; set; }
        public string PromotionDetails { get; set; }
        public int? PromotionDiscoun { get; set; }
        public DateTime? PromotionStartdate { get; set; }
        public DateTime? PromotionLastdate { get; set; }
        public string RaftId { get; set; }
        public string RaftName { get; set; }
        public string RaftDetails { get; set; }
        public int? RaftPrice { get; set; }
        public int StatusBId { get; set; }
        public string StatusBName { get; set; }
        public int SorderId { get; set; }
        public string SorderName { get; set; }
        public int SpromotionId { get; set; }
        public string SpromotionName { get; set; }
        public string UserTel { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string OrderId { get; set; }
        public DateTime? OrderDate { get; set; }
        public string OrderImageDeposit { get; set; }
        public int? OrderPrice { get; set; }
        public int? OrderDeposit { get; set; }
        public string OrderImagePay { get; set; }
        public int? OrderPay { get; set; }
        public string OsId { get; set; }
        public string OrderDetailsId { get; set; }
        public int? OrderDetailsPrice { get; set; }
    }
}